### ISSUE TITLE
Modify the JPF Partial Transition System Listener

### ISSUE THREAD

**Issue by matthewwalk** [Lassonde-JPF/jpf-ctl#13]
## Description
Presently, the listener prints the DOT representation of the partial transition system. This is not necessary for the production build; and therefore should be removed. Furthermore, there needs to be increased detail in the text output for the partial transition system. Lastly, a more robust testing system needs to be developed as follows:
* Generate a random directed graph (See [Erdos Renyi Graph](https://www.cs.purdue.edu/homes/dgleich/demos/erdos_renyi/generate.html))
* Convert the graph into java code (Using switch statements, if statements, etc.)
* Randomly select a value for `max_new_states` 
* Perform a DFS on the graph and record relevant data (states visited, states not visited, etc.)
* Test the listener on the random graph
* Compare the results from the listener (Actual) against the data gathered by the DFS (expected)
* Perform this operation `N` times

## Task List
- [x] Remove DOT functionality and refactor remaining listener code
- [x] Implement additional functionality for the text/file output
- [x] Implement the random directed graph generator
- [x] Implement the Compiler/Loader for the generated graphs
- [x] Implement the relevant test cases
- [x] Fix the issue with expected/actual output
- [x] Check the listener works when using a BFS
- [x] Implement the Native Peer ( inject Graph.random, double check naming, declare Graph as native)
- [x] Re-test

## Additional Details
The project utilizes gradle to identify the user's installed version of JPF and use it to run the test cases. While this is not needed for the actual listener (as it can simply be exported individually) it is very useful for development.
